### ISSUE TITLE
IndexError on ECS fields in Elasticsearch

### ISSUE THREAD

**Issue by webhead404** [Nclose-ZA/elastalert_hive_alerter#11]
I am attempting to generate alerts via theHive for an ECS compatible index. For context, the fields are nested. Example rule below:

```
description: Sends SIEM alerts to theHive
filter:
- query:
    query_string:
      query: (alert.rule.severity:"high")
index: security-index-*
name: New-High-SeverityAlert-SIEM
priority: 2
realert:
  minutes: 0
type: any

alert: hivealerter

hive_connection:
  hive_host: http://$IP
  hive_port: $PORT
  hive_apikey: $APIKEY


hive_alert_config:
  title: '{rule[alert][rule][name]}'
  type: 'external'
  source: 'Elastic-SIEM'
  severity: 2
  tags: ['elastalert']
  tlp: 3
  status: 'New'
  follow: True
```

Traceback: 
`Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]: ERROR:root:Traceback (most recent call last):
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:   File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1450, in alert
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:     return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:   File "/usr/local/lib/python3.6/dist-packages/elastalert-0.2.1-py3.6.egg/elastalert/elastalert.py", line 1544, in send_alert
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:     alert.alert(matches)
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:   File "/usr/local/lib/python3.6/dist-packages/elastalert_hive_alerter-1.0.0rc2-py3.6.egg/elastalert_hive_alerter/hive_alerter.py", line 88, in alert
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:     alert_config = self.create_alert_config(matches[0])
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:   File "/usr/local/lib/python3.6/dist-packages/elastalert_hive_alerter-1.0.0rc2-py3.6.egg/elastalert_hive_alerter/hive_alerter.py", line 56, in create_alert_config
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]:     alert_config[alert_config_field] = alert_config_value.format(**context)
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]: IndexError: tuple index out of range
Mar 25 13:02:38 elkhunter-virtual-machine elastalert[116606]: ERROR:root:Uncaught exception running rule New-High-SeverityAlert-SIEM: tuple index out of range`
