### ISSUE TITLE
Custom Fields for Alert

### ISSUE THREAD

**Issue by kellenhopwood** [Nclose-ZA/elastalert_hive_alerter#6]
Alerts now have the ability to use custom fields. (https://GitHub.com/thehive-project/thehive/issues/635), is it possible to integrate this into the alerter?

**Comment by danielbrowne** [comment]
It looks like `customFields` has already been added to TheHive4Py, so I suspect it is probably possible to add a `customFields` key to `rule["hive_alert_config"]` and it should get put into the alert that gets created. I'm not really sure what should go into that field, but perhaps you can give that a try and see if it works for you?

**Comment by kellenhopwood** [comment]
I've been playing with it for a while now, and I think I figured out on a high level how everything has to go together.  For whatever reason, theHive4py doesn't accept just a custom fields dictionary, so they created a custom function to add the fields.  I was able to import that into Alerts.py, but I think a new mapping is required similar to the observable_data_mapping.  

In the sample alert file this is how they append customfields:
```# Prepare the custom fields
customFields = CustomFieldHelper()\
    .add_boolean('booleanField', True)\
    .add_string('businessImpact', 'HIGH')\
    .add_date('occurDate', int(time.time())*1000)\
    .add_number('cvss', 9)\
    .build()
# Prepare the sample Alert
sourceRef = str(uuid.uuid4())[0:6]
alert = Alert(title='New Alert',
              tlp=3,
              tags=['TheHive4Py', 'sample'],
              description='N/A',
              type='external',
              source='instance1',
              sourceRef=sourceRef,
              artifacts=artifacts,
              customFields=customFields)
```
Ref: https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-alert-create.py

I tried to use the Observable mapping code to then create a custom field mapping.  

```
for mapping in self.rule.get('hive_custom_field_mapping', []):
    for field_type, match_data_key in mapping.iteritems():
          try:
                match_data_keys = re.findall(r'\{match\[([^\]]*)\]', match_data_key)
                if all([True for k in match_data_keys if k in context['match']]):
                    customFields=CustomFieldsHelper.add_string(field_type, match_data_key.format(**context)))
           except KeyError:
                raise KeyError('\nformat string\n{}\nmatch data\n{}'.format(match_data_key, context))
           try:
	        customFields=CustomFieldsHelper.build()
          except:
                print('Error in building CustomFieldsHelper')
```

**Comment by danielbrowne** [comment]
I think it will go in hive_alert_config rather than hive_observable_data_mapping. I have created https://github.com/Nclose-ZA/elastalert_hive_alerter/pull/7 which I think should add the functionality you need. @markus-nclose @mpotgieter

**Comment by danielbrowne** [comment]
Change is merged.

**Comment by kellenhopwood** [comment]
Hey, @danielbrowne I appreciate the quick implementation, I was playing with the new functionality, but I haven't been able to figure out how to get it working, if you can help me implement it I'll be sure to draw up some documentation. 
My rule file:
```
import: /etc/elastalert/config.yaml
index: "*-sysmon-*"
name: "RuleTester"
type: any
include: ['hash_sha256','process_parent_command_line','Client', 'host_name','process_path']
filter:
   - query_string:
       query: process_parent_command_line:"net localgroup administrators"
alert: hivealerter
hive_alert_config:
    title: '{rule[name]}'
    type: 'external'
    source: 'Elastalert'
    description: 'A User on a {match[Client]} machine attempted to run the command {match[process_parent_command_line]}'
    severity: 1
    tags: ['Security Alert','Suspicious','Rule Test', '{match[Client]}', '_id:{match[_id]}']
    tlp: 2
    status: 'New'
    follow: True
    customFields: {
                    'applicationPath': {'type': 'string', 'value': 'process_path'},
                }
hive_observable_data_mapping:
    - hash: '{match[hash_sha256]}'
```
This rule functions flawlessly, in elastalert testing, and in application:

There don't appear to be any fields where I expected them to be.

**Comment by danielbrowne** [comment]
I think you will need to pull the field you want out of the match in a similar way to what you have done in "tags", eg.

`customFields: {'applicationPath': {'type': 'string', 'value': '{match[process_path]}'},}`

**Comment by kellenhopwood** [comment]
I tried with the `'{match[variable name]}'` syntax, but I also tried with a simple string to try and determine the root cause, even when the variable was `'test'` I wasn't able to get it to properly send the data.

**Comment by danielbrowne** [comment]
Is there any chance you could capture the data that is being matched by the rule? Perhaps that will clarify the issue. Can you also confirm that the unit tests run correctly for you if you run `python setup.py test`?

**Comment by kellenhopwood** [comment]
The output from my rules test is this, it shows what it matches.
```
elastalert - {'alert_info': {'type': 'HiveAlerter', 'hive_host': 'http://localhost'}, 'alert_sent': True, 'match_body': {'_type': u'doc', u'process_path': u'C:\\Windows\\System32\\net1.exe', u'process_parent_command_line': u'net  localgroup administrators', '_index': u'remote-test-client-sysmon-11.2018', 'num_hits': 1, u'@timestamp': '2018-11-07T14:12:50.589Z', u'Client': u'remote-test-client', u'host_name': u'DESKTOP-KEC9JR3', 'num_matches': 1, '_id': u'729137130', u'hash_sha256': u'FFC30745BE3B6C2771FC4B2993CFF50B5226B271C412467E97B1DC1086DEA888'}, 'rule_name': 'RuleTester', 'match_time': '2018-11-07T14:12:50.589Z', 'alert_time': datetime.datetime(2018, 11, 7, 14, 18, 20, 293688, tzinfo=tzutc())}

elastalert_status - {'hits': 1, 'matches': 1, '@timestamp': datetime.datetime(2018, 11, 7, 14, 18, 21, 319732, tzinfo=tzutc()), 'rule_name': 'RuleTester', 'starttime': datetime.datetime(2018, 11, 6, 14, 18, 19, 725776, tzinfo=tzutc()), 'endtime': datetime.datetime(2018, 11, 7, 14, 18, 19, 725776, tzinfo=tzutc()), 'time_taken': 1.5875749588012695}
```
the data that it carves:
```
@timestamp: 2018-11-07T14:12:50.589Z
Client: remote-test-client
_id: 729137130
_index: remote-test-client-sysmon-11.2018
_type: doc
hash_sha256: FFC30745BE3B6C2771FC4B2993CFF50B5226B271C412467E97B1DC1086DEA888
host_name: DESKTOP-KEC9JR3
num_hits: 1
num_matches: 1
process_parent_command_line: net  localgroup administrators
process_path: C:\Windows\System32\net1.exe
```

It looks like it has the proper fields to pull from, but when I pull the alerts via api, or look at them in the gui:
![image](https://user-images.githubusercontent.com/44026330/48136989-0781e280-e26f-11e8-9115-ae81a85d233c.png)
The JSON of the alert pulled from thehive:

**Comment by danielbrowne** [comment]
If I use the match data above as input data for my unit test, this is the data that the alerter sends to TheHive4Py (which is as specified by the documentation):

`{u'status': u'New', u'tlp': 3, u'severity': 2, u'title': u'test_rule_name', u'artifacts': [u'fake_artifact_return', u'fake_artifact_return',  
u'fake_artifact_return', u'fake_artifact_return', u'fake_artifact_return'], u'tags': [u'TheHive4Py', u'sample test_rule_name'], u'sourceRef': 
'123456', u'source': u'instance1', u'follow': True, u'customFields': {u'test_string': {'order': 4, 'string': u'test2.com'}, u'test_path':     
{'order': 1, 'string': u'C:\\Windows\\System32\net1.exe'}, u'test_boolean': {'boolean': u'True', 'order': 2}, u'test_date': {'date':          
u'1541658396000', 'order': 3}, u'test_number': {'order': 0, 'number': u'123'}}, u'type': u'external', u'description':                         
u'test_rule_name\ntest.com Test desc'}`

However this is a mocked test, and unfortunately I won't have time until Monday to spin up an instance of TheHive in order to test this properly. I might be able to provide a quick answer for this specific case given a) the contents of "matches" at line 19 and b) the contents of "alert_config" at line 70 when your rule sends a match to this alerter.

**Comment by kellenhopwood** [comment]
I think the issue might be something to do with ingesting the fields into thehive, if I were to put the same matches into tags, it would work fine, but Custom field won't appear in thehive.

**Comment by kellenhopwood** [comment]
@danielbrowne were you able to reproduce my issue, I've been fiddling with it but I haven't gotten it properly functional.

**Comment by danielbrowne** [comment]
Hi, apologies, I have been completely swamped with a major project at work and have not had time to look into this. I will try to investigate the issue on Wednesday evening.

**Comment by markus-nclose** [comment]
@kellenhopwood Did you manage to test again with the working config file above?

**Comment by markusza** [comment]
What was the error?
Perhaps try a fresh install in a Python venv and see if that makes a difference?

**Comment by kellenhopwood** [comment]
I don't get an Error, it just doesn't include the customfield in an alert (sorry for the inconsistent variable names we use a slightly different naming convention)
`elastalert - {'alert_info': {'type': 'HiveAlerter', 'hive_host': 'http://localhost'}, 'alert_sent': True, 'match_body': {'_type': u'doc', u'process_path': u'C:\\Windows\\System32\\net1.exe', u'process_parent_command_line': u'net  localgroup administrators', '_index': u'remote-test-client-sysmon-12.2018', 'num_hits': 11, u'@timestamp': '2018-12-14T16:53:36.810Z', u'Client': u'remote-test-client', u'host_name': u'DESKTOP-EJD4TOF', 'num_matches': 11, '_id': u'336025684', u'hash_sha256': u'C687157FD58EAA51757CDA87D06C30953A31F03F5356B9F5A9C004FA4BAD4BF5'}, 'rule_name': 'RuleTester', 'match_time': '2018-12-14T16:53:36.810Z', 'alert_time': datetime.datetime(2018, 12, 14, 19, 18, 17, 784310, tzinfo=tzutc())}`

```
import: /etc/elastalert/config.yaml
index: "*-sysmon-*"
name: "RuleTester"
type: any
include: ['hash_sha256','process_parent_command_line','Client', 'host_name','process_path']
filter:
   - query_string:
       query: process_parent_command_line:"net localgroup administrators"
alert: hivealerter
hive_alert_config:
    title: '{rule[name]}'
    type: 'external'
    source: 'Elastalert'
    description: 'A User on a {match[Client]} machine attempted to run the command {match[process_parent_command_line]}'
    severity: 1
    tags: ['Security Alert','Suspicious','Rule Test', '{match[Client]}', '_id:{match[_id]}']
    tlp: 2
    status: 'New'
    follow: True
    customFields: {'sha256':{'type':'string','value':'{match[hash_sha256]}'}}
hive_observable_data_mapping:
  - hash: "{match[hash_sha256]}"
  - hostname: "{match[host_name]}"
```
It properly creates all the other fields and values, except for custom fields which doesn't appear at all, it's not an empty dictionary, it just fails to create it.
